// <auto-generated />
namespace WebGame.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateGame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateGame));
        
        string IMigrationMetadata.Id
        {
            get { return "201711111606279_CreateGame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
